# Generated by Django 5.2.4 on 2025-07-22 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_completed', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_keywords', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
                'indexes': [models.Index(fields=['is_flagged', 'upload_timestamp'], name='reports_doc_is_flag_eedac2_idx'), models.Index(fields=['risk_score'], name='reports_doc_risk_sc_b67fb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScamReportEnhanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('message', 'Suspicious Message'), ('url', 'Suspicious URL'), ('phone', 'Suspicious Phone Number')], max_length=20)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('flagged_patterns', models.JSONField(blank=True, default=list)),
                ('submitted_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_timestamp'],
                'indexes': [models.Index(fields=['report_type', 'risk_level'], name='reports_sca_report__747a33_idx'), models.Index(fields=['submitted_timestamp'], name='reports_sca_submitt_bcb9f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('trend_direction', models.CharField(choices=[('up', 'Increasing'), ('down', 'Decreasing'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('risk_correlation', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-analysis_date', '-frequency'],
                'unique_together': {('analysis_date', 'keyword')},
            },
        ),
    ]
